### ISSUE TITLE
UI (almost) endlessly reloads, when running containerized from Kubernetes cluster of several pods

### ISSUE THREAD

**Issue by cernier** [vaadin/base-starter-flow-quarkus#19]
### Description of the bug

Despite one of the **Quarkus** advantages is to deploy and run natively in cloud applications packaged as containerized Docker image, it appears that the Vaadin integration of Quarkus and/or this starter sample is not ready for this purpose.

Indeed, whereas there is **no issue** when running it packaged as Docker image deployed to a **single-pod/replica Kubernetes cluster**, if it's deployed to a **multi-pods/replicas one**, the **UI (almost) endlessly reloads** so that it's obviously not usable at all.
"almost" means that, sometimes, the reload loop stopped and the last load completes fine.

### Expected behavior

UI should be usable and loads fine, without such endlessly reloading, whatever the number of pods/replicas of the Kubernetes cluster, like it's the case for just 1:

Deploy directly and quickly on Okteto 🟢 **working** Dockerized sample ([`1-dockerized-pod` branch of my fork](https://github.com/cernier/base-starter-flow-quarkus/tree/1-dockerized-pod)): [![Develop on Okteto](https://okteto.com/develop-okteto.svg)](https://cloud.okteto.com/deploy?repository=https://github.com/cernier/base-starter-flow-quarkus&branch=1-dockerized-pod)

### Minimal reproducible example

Deploy directly and quickly on Okteto 🔴 **failing** Dockerized sample ([`2-dockerized-pods` branch of my fork](https://github.com/cernier/base-starter-flow-quarkus/tree/2-dockerized-pods)): [![Develop on Okteto](https://okteto.com/develop-okteto.svg)](https://cloud.okteto.com/deploy?repository=https://github.com/cernier/base-starter-flow-quarkus&branch=2-dockerized-pods)

### Versions
* Vaadin / Flow version: 22+
* Quarkus version: Quarkus 2+

**Comment by mstahv** [comment]
My quick guess is that the ingress/loadbalancer in your K8s clusters needs to be configured for session affinity aka sticky sessions. This is what start.vaadin.com generates for Spring Boot apps, something similar might work in your setup (I have never used Okteto).

```
apiVersion: v1
kind: Service
metadata:
  name: myapp-balancer
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
```
